// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed_TFT

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Speedo
void ui_Speedo_screen_init(void);
lv_obj_t * ui_Speedo;
lv_obj_t * ui_SpeedArc;
lv_obj_t * ui_SpeedNumBackGround;
lv_obj_t * ui_SpeedNum;
lv_obj_t * ui_TimeBackGround;
lv_obj_t * ui_Time;
lv_obj_t * ui_DateBackGround;
lv_obj_t * ui_Date;
lv_obj_t * ui_LabelMPH;
lv_obj_t * ui_SatImg;
lv_obj_t * ui_SatNumBackGround;
lv_obj_t * ui_SatNum;
lv_obj_t * ui_Heading;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_1958355215[1] = {&ui_img_1946256235};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Speedo_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Speedo);
}
