// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed

#ifndef _GPS_SPEED_UI_H
#define _GPS_SPEED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_textGPS;
extern lv_obj_t * ui_textSpeed;
extern lv_obj_t * ui_labelSpeed;
extern lv_obj_t * ui_textHeading;
extern lv_obj_t * ui_labelHeading;
extern lv_obj_t * ui_FRS;
extern lv_obj_t * ui_labelTime;
extern lv_obj_t * ui_labelDate;
extern lv_obj_t * ui_textSats;
extern lv_obj_t * ui_labelSats;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_frs_png);    // assets/frs.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
