// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed_TFT

#ifndef _GPS_SPEED_TFT_UI_H
#define _GPS_SPEED_TFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Speedo
void ui_Speedo_screen_init(void);
extern lv_obj_t * ui_Speedo;
extern lv_obj_t * ui_SpeedNumBackGround;
extern lv_obj_t * ui_SpeedNum;
extern lv_obj_t * ui_TimeBackGround;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_DateBackGround;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_LabelMPH;
extern lv_obj_t * ui_SatImg;
extern lv_obj_t * ui_SatNumBackGround;
extern lv_obj_t * ui_SatNum;
extern lv_obj_t * ui_Heading;
extern lv_obj_t * ui_SpeedChart;
extern lv_obj_t * ui_SpeedChart_Xaxis;
extern lv_obj_t * ui_SpeedChart_Yaxis1;
extern lv_obj_t * ui_SpeedChart_Yaxis2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1946256235);    // assets/satellite-antenna-emoji-20x25.png

// FONTS
LV_FONT_DECLARE(ui_font_Digital_Mono_10);
LV_FONT_DECLARE(ui_font_Digital_Mono_16);
LV_FONT_DECLARE(ui_font_Digital_Mono_72);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
