// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed

#ifndef _UI_COMP_LABELSPEED_H
#define _UI_COMP_LABELSPEED_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT labelSpeed
#define UI_COMP_LABELSPEED_LABELSPEED 0
#define _UI_COMP_LABELSPEED_NUM 1
lv_obj_t * ui_labelSpeed_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
