// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed

#include "ui.h"

void ui_comp_labelSpeed_create_hook(lv_obj_t * comp)
{
}
