// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed

#include "ui.h"


// COMPONENT labelSpeed

lv_obj_t * ui_labelSpeed_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_labelSpeed;
    cui_labelSpeed = lv_label_create(comp_parent);
    lv_obj_set_width(cui_labelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_labelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_labelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(cui_labelSpeed, "000");
    lv_obj_remove_flag(cui_labelSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_LABELSPEED_NUM);
    children[UI_COMP_LABELSPEED_LABELSPEED] = cui_labelSpeed;
    lv_obj_add_event_cb(cui_labelSpeed, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_labelSpeed, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_labelSpeed_create_hook(cui_labelSpeed);
    return cui_labelSpeed;
}

