// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x323136), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textGPS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textGPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textGPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textGPS, 1);
    lv_obj_set_y(ui_textGPS, -82);
    lv_obj_set_align(ui_textGPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textGPS, "GPS DATA");
    lv_obj_remove_flag(ui_textGPS, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_textGPS, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSpeed = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_textSpeed, 180);
    lv_obj_set_height(ui_textSpeed, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_textSpeed, 0);
    lv_obj_set_y(ui_textSpeed, -29);
    lv_obj_set_align(ui_textSpeed, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_textSpeed, "Speed:         mph");
    lv_textarea_set_placeholder_text(ui_textSpeed, "Placeholder...");
    lv_textarea_set_one_line(ui_textSpeed, true);
    lv_obj_remove_flag(ui_textSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_textSpeed, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_labelSpeed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSpeed, -12);
    lv_obj_set_y(ui_labelSpeed, -29);
    lv_obj_set_align(ui_labelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSpeed, "000");
    lv_obj_set_style_text_align(ui_labelSpeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textHeading = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_textHeading, 180);
    lv_obj_set_height(ui_textHeading, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_textHeading, 0);
    lv_obj_set_y(ui_textHeading, 11);
    lv_obj_set_align(ui_textHeading, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_textHeading, "Heading:");
    lv_textarea_set_placeholder_text(ui_textHeading, "Placeholder...");
    lv_textarea_set_one_line(ui_textHeading, true);
    lv_obj_remove_flag(ui_textHeading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_textHeading, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textHeading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_labelHeading = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelHeading, 5);
    lv_obj_set_y(ui_labelHeading, 11);
    lv_obj_set_align(ui_labelHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHeading, "NNW");
    lv_obj_set_style_text_align(ui_labelHeading, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRS = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_FRS, &ui_img_frs_png);
    lv_obj_set_width(ui_FRS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRS, 1);
    lv_obj_set_y(ui_FRS, 66);
    lv_obj_set_align(ui_FRS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FRS, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_FRS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTime, 45);
    lv_obj_set_y(ui_labelTime, -57);
    lv_obj_set_align(ui_labelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTime, "24:59:59");
    lv_obj_set_style_text_font(ui_labelTime, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDate, -38);
    lv_obj_set_y(ui_labelDate, -57);
    lv_obj_set_align(ui_labelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDate, "11/17/2024");
    lv_obj_set_style_text_font(ui_labelDate, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSats = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textSats, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSats, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSats, -8);
    lv_obj_set_y(ui_textSats, 98);
    lv_obj_set_align(ui_textSats, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textSats, "Sats:");
    lv_obj_set_style_text_font(ui_textSats, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSats = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelSats, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSats, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSats, 10);
    lv_obj_set_y(ui_labelSats, 98);
    lv_obj_set_align(ui_labelSats, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSats, "00");
    lv_obj_set_style_text_font(ui_labelSats, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labelSats, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labelSats, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
