// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GPS_Speed_TFT

#include "ui.h"

void ui_Speedo_screen_init(void)
{
    ui_Speedo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Speedo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Speedo, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Speedo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedArc = lv_arc_create(ui_Speedo);
    lv_obj_set_width(ui_SpeedArc, 230);
    lv_obj_set_height(ui_SpeedArc, 230);
    lv_obj_set_align(ui_SpeedArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SpeedArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_SpeedArc, 0, 140);
    lv_arc_set_value(ui_SpeedArc, 70);
    lv_arc_set_bg_angles(ui_SpeedArc, 180, 0);

    lv_obj_set_style_arc_color(ui_SpeedArc, lv_color_hex(0xC42F00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedArc, lv_color_hex(0xC42F00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedNumBackGround = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_SpeedNumBackGround, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedNumBackGround, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedNumBackGround, 0);
    lv_obj_set_y(ui_SpeedNumBackGround, -50);
    lv_obj_set_align(ui_SpeedNumBackGround, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedNumBackGround, "888");
    lv_obj_remove_flag(ui_SpeedNumBackGround,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SpeedNumBackGround, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedNumBackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedNumBackGround, &ui_font_Digital_Mono_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedNum = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_SpeedNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedNum, 0);
    lv_obj_set_y(ui_SpeedNum, -50);
    lv_obj_set_align(ui_SpeedNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedNum, "888");
    lv_obj_remove_flag(ui_SpeedNum, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SpeedNum, lv_color_hex(0xC42F00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedNum, &ui_font_Digital_Mono_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeBackGround = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_TimeBackGround, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeBackGround, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeBackGround, 0);
    lv_obj_set_y(ui_TimeBackGround, 100);
    lv_obj_set_align(ui_TimeBackGround, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeBackGround, "88:88:88");
    lv_obj_remove_flag(ui_TimeBackGround,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TimeBackGround, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeBackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeBackGround, &ui_font_Digital_Mono_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 0);
    lv_obj_set_y(ui_Time, 100);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "88:88:88");
    lv_obj_remove_flag(ui_Time, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &ui_font_Digital_Mono_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateBackGround = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_DateBackGround, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateBackGround, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateBackGround, 0);
    lv_obj_set_y(ui_DateBackGround, 80);
    lv_obj_set_align(ui_DateBackGround, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateBackGround, "8888/88/88");
    lv_obj_remove_flag(ui_DateBackGround,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DateBackGround, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateBackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateBackGround, &ui_font_Digital_Mono_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 0);
    lv_obj_set_y(ui_Date, 80);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "8888/88/88");
    lv_obj_remove_flag(ui_Date, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &ui_font_Digital_Mono_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMPH = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_LabelMPH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMPH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMPH, 68);
    lv_obj_set_y(ui_LabelMPH, -32);
    lv_obj_set_align(ui_LabelMPH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMPH, "MPH");
    lv_obj_remove_flag(ui_LabelMPH, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelMPH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SatImg = lv_image_create(ui_Speedo);
    lv_image_set_src(ui_SatImg, &ui_img_1946256235);
    lv_obj_set_width(ui_SatImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SatImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SatImg, 68);
    lv_obj_set_y(ui_SatImg, -10);
    lv_obj_set_align(ui_SatImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SatImg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_SatImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_SatNumBackGround = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_SatNumBackGround, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SatNumBackGround, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SatNumBackGround, 84);
    lv_obj_set_y(ui_SatNumBackGround, -1);
    lv_obj_set_align(ui_SatNumBackGround, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SatNumBackGround, "88");
    lv_obj_add_flag(ui_SatNumBackGround, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_SatNumBackGround,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SatNumBackGround, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SatNumBackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SatNumBackGround, &ui_font_Digital_Mono_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SatNum = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_SatNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SatNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SatNum, 84);
    lv_obj_set_y(ui_SatNum, -1);
    lv_obj_set_align(ui_SatNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SatNum, "05");
    lv_obj_add_flag(ui_SatNum, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_SatNum, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_SatNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SatNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SatNum, &ui_font_Digital_Mono_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Heading = lv_label_create(ui_Speedo);
    lv_obj_set_width(ui_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Heading, 171);
    lv_obj_set_y(ui_Heading, -45);
    lv_obj_set_align(ui_Heading, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Heading, "WNW");
    lv_obj_remove_flag(ui_Heading, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Heading, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);


}
